language: python

notifications:
  email:
    recipients:
      - alexandra.diem@gmail.com
    on_success: never   # default: change
    on_failure: always  # default: always

matrix:
    include:
        - os: linux
          python: 3.7


install:
  - sudo apt-get update

  # Install conda
  - wget "https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda

  # Export path
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r

  # Set conda parameters
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge

  # Set up environment
  - conda create -n m3h3 pulse pytest

  # Activate environment
  - source activate m3h3
  - python setup.py install

  # Useful for debugging any issues with conda
  - conda info -a

script:
  - pytest tests/.
