language: python

notifications:
  email:
    recipients:
      - alexandra.diem@gmail.com
    on_success: never   # default: change
    on_failure: always  # default: always

matrix:
    include:
        - os: linux
          python: 3.7

# blocklist
branches:
  except:
  - docs
  - develop

# safelist
branches:
  only:
  - master


install:
  - sudo apt-get update

  # Install conda
  - wget "https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda

  # Export path
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r

  # Set conda parameters
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge

  # Set up environment
  - conda create -n m3h3 fenics

  # Activate environment
  - source activate m3h3
  - pip uninstall h5py
  - pip install -r requirements.txt
  - pip install git+https://github.com/ComputationalPhysiology/fenics-geometry.git
  - pip install hg+https://bitbucket.org/meg/cbcbeat
  - python setup.py install

  # Useful for debugging any issues with conda
  - conda info -a

script:
  - pytest tests/.
